name: planeformers
channels:
  - pytorch3d
  - bottler
  - iopath
  - fvcore
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.4=py37hce1f21e_0
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.6.15=py37h06a4308_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - fvcore=0.1.5.post20210915=py37
  - giflib=5.2.1=h7b6447c_0
  - glib=2.56.2=hd408876_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.9=py37
  - jpeg=9e=h7f8727e_0
  - kiwisolver=1.4.2=py37h295c915_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.1=py37h06a4308_1
  - matplotlib-base=3.5.1=py37ha18d171_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.8.1=py37h807cd23_2
  - nvidiacub=1.10.0=0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1p=h5eee18b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py37h8c16a72_0
  - pcre=8.45=h295c915_0
  - pillow=9.0.1=py37h22f2fdc_0
  - pip=21.2.2=py37h06a4308_0
  - portalocker=2.5.0=py37h89c1867_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h22d08a2_1
  - python=3.7.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.10.1=py3.7_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.6.2=py37_cu102_pyt1101
  - pytz=2022.1=py37h06a4308_0
  - pyyaml=6.0=py37h540881e_4
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - scipy=1.7.3=py37hc147768_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - setuptools=59.5.0
  - sip=6.5.1=py37h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=hc218d9a_0
  - tabulate=0.8.10=pyhd8ed1ab_0
  - termcolor=1.1.0=pyhd8ed1ab_3
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchvision=0.11.2=py37_cu102
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip
  - pip:
    - absl-py==1.1.0
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - attrs==21.4.0
    - black==21.4b2
    - cachetools==5.2.0
    - charset-normalizer==2.1.0
    - click==8.1.3
    - cloudpickle==2.1.0
    - cython==0.29.30
    - future==0.18.2
    - google-auth==2.9.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - hydra-core==1.2.0
    - idna==3.3
    - imageio==2.19.3
    - importlib-metadata==4.12.0
    - importlib-resources==5.8.0
    - iniconfig==1.1.1
    - joblib==1.1.0
    - llvmlite==0.38.1
    - mapbox-earcut==1.0.0
    - markdown==3.3.7
    - mypy-extensions==0.4.3
    - networkx==2.6.3
    - nose==1.3.7
    - numba==0.55.2
    - numpy==1.19.2
    - numpy-quaternion==2020.9.5.14.42.2
    - oauthlib==3.2.0
    - omegaconf==2.2.2
    - opencv-contrib-python==4.4.0.46
    - pathspec==0.9.0
    - pluggy==1.0.0
    - protobuf==3.19.4
    - py==1.11.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pydot==1.4.2
    - pytest==7.1.2
    - pywavelets==1.3.0
    - regex==2022.7.9
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-image==0.15.0
    - scikit-learn==0.21.3
    - spherecluster==0.1.7
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tomli==2.0.1
    - typed-ast==1.5.4
    - urllib3==1.26.10
    - werkzeug==2.1.2
    - zipp==3.8.0
    - -r requirements.txt
